In [1]:
import torch
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
z = torch.FloatTensor([1,2,3])

In [4]:
hypothesis = F.softmax(z, dim =0) # 3개의 원소의 값이 0과 1사이의 값을 가지는 벡터로 변환되었다.

In [5]:
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [8]:
hypothesis.sum() # 확률 총합 1 

tensor(1.)

In [9]:
z = torch.rand(3,5, requires_grad=True) # 3x5 행렬의 크기를 가진 텐서 만들기

In [11]:
hypothesis = F.softmax(z, dim=1) # dim =1 두번째 차원에 대해서 소프트맥스 함수를 적용한다.

In [12]:
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [13]:
y = torch.randint(5,(3,)).long() # 3개의 샘플에 대해서 5개의 클래스 중 어떤 클레스가 정답인지 예측한 결과.

In [14]:
print(y)

tensor([0, 2, 1])


In [17]:
y_one_hot = torch.zeros_like(hypothesis) # 모든 원소가 0의 값을 가진 3x5 텐서 생성
y_one_hot.scatter_(1, y.unsqueeze(1), 1) # unsqueeze(1)를 하면 (3,)의 크기를 가졌던 y텐서를 (3x1)텐서가 된다.

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [19]:
print(y.unsqueeze(1))

tensor([[0],
        [2],
        [1]])


In [20]:
print(y_one_hot)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])


In [21]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean() # sum(dim=1)구현 , 평균 = mean으로 구현
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


In [22]:
torch.log(F.softmax(z,dim=1)) # 함수의 결과에 로그를 씌웠다. 출력값을 로그함수의 입력값으로 사용

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward>)

In [23]:
F.log_softmax(z, dim=1) # log와 softmax를 하나로 구현해놓은 파이토치 내장함수

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward>)

In [24]:
(y_one_hot * -F.log_softmax(z, dim =1)).sum(dim=1).mean()

tensor(1.4689, grad_fn=<MeanBackward0>)

In [25]:
F.nll_loss(F.log_softmax(z, dim=1), y) # F.nll_loss를 사용하면 원핫벡터를 넣을 필요없이 바로 실제값을 인자로 사용한다

tensor(1.4689, grad_fn=<NllLossBackward>)

In [26]:
F.cross_entropy(z, y) # F.nll_loss 와 F.log_softmax를 둘다 포함한다.

tensor(1.4689, grad_fn=<NllLossBackward>)