In [37]:
import torch
import numpy as np

In [2]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [3]:
print(t.dim())

1


In [4]:
print(t.shape)

torch.Size([7])


In [5]:
print(t.size())

torch.Size([7])


In [7]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([4, 3])
torch.Size([4, 3])


In [10]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [12]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [13]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape) 
print(m1.matmul(m2)) # 행렬 곱셈

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [14]:
print(m1*m2)
print(m1.mul(m2)) #element-wise 곱셈

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [15]:
t = torch.FloatTensor([1,2])
print(t.mean()) # 평균값

tensor(1.5000)


In [18]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
print(t.mean())

tensor(2.5000)


In [20]:
print(t.mean(dim=0)) # 차원을 인자로 주었다. 즉 해당차원을 제거한다는 의미

tensor([2., 3.])


In [21]:
t.mean(dim=0)

tensor([2., 3.])

In [22]:
print(t.mean(dim=1)) # 열의 차원을 제거한다. 2,2, 에서 2,1 이된다.

tensor([1.5000, 3.5000])


In [23]:
print(t.mean(dim=-1)) # dimension -1 은 마지막 차원을 의미한다.

tensor([1.5000, 3.5000])


In [26]:
print(t.sum())
print(t.sum(dim=0)) # 행의 차원 제거
print(t.sum(dim=1)) # 열의 차원 제거 
print(t.sum(dim=-1)) # 열의 차원 제거 

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [27]:
print(t.max()) # 원소중 최대값 리턴

tensor(4.)


In [28]:
print(t.max(dim=0)) # 행의 차원 제거

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [29]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [30]:
print(t.max(dim=1)) # 열의 차원제거
print(t.max(dim=-1)) # 열의 차원제거

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [38]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [39]:
print(ft.shape)

torch.Size([2, 2, 3])


In [40]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경, -1 은 torch에게 맡긴다.
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [41]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) # 2*2*3 = x * 1 * 3 -> x = 4 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [42]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [43]:
print(ft.squeeze())
print(ft.squeeze().shape) # squeeze 해당 차원이 1 인경우 해당 차원을 제거한다.

tensor([0., 1., 2.])
torch.Size([3])


In [46]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) # unsqueeze 특정위치에 1인 차원을 추가할 수 있습니다.

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [47]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [48]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [49]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [50]:
lt = torch.LongTensor([1, 2, 3, 4]) #long type casting
print(lt)
print(lt.float()) # long type -> float type

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [51]:
bt = torch.ByteTensor([True, False, False, True]) # byte type
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [52]:
print(bt.long()) # byte to long
print(bt.float()) # byte to float

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [53]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x,y],dim=0)) #연결하기 concatenate dim=0 첫번쨰 차원 늘리기 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [54]:
print(torch.cat([x,y],dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [55]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6]) # stacking 에 이용할 벡터들
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [56]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)) # 이 연산을 한번에 할 수 있는 것이 stack 이다.


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [57]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [60]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

print(torch.ones_like(x)) #onse_like 동일한 크기 1로 채워진 텐서 생성
print(torch.zeros_like(x)) #zeros_like 동일한 크기 0으로 채워진 텐서 생성

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [61]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 각 원소에 2를 곱한값 출력
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [62]:
print(x.mul_(2.)) # num_ 를 사용하면 연산후 기존의 값을 덮어쓰기한다.
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
